# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shiv/HTTPserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shiv/HTTPserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shiv/HTTPserver/CMakeFiles /home/shiv/HTTPserver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shiv/HTTPserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.s
.PHONY : main.cpp.s

src/ChatRoom.o: src/ChatRoom.cpp.o
.PHONY : src/ChatRoom.o

# target to build an object file
src/ChatRoom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ChatRoom.cpp.o
.PHONY : src/ChatRoom.cpp.o

src/ChatRoom.i: src/ChatRoom.cpp.i
.PHONY : src/ChatRoom.i

# target to preprocess a source file
src/ChatRoom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ChatRoom.cpp.i
.PHONY : src/ChatRoom.cpp.i

src/ChatRoom.s: src/ChatRoom.cpp.s
.PHONY : src/ChatRoom.s

# target to generate assembly for a file
src/ChatRoom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/ChatRoom.cpp.s
.PHONY : src/ChatRoom.cpp.s

src/Database.o: src/Database.cpp.o
.PHONY : src/Database.o

# target to build an object file
src/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Database.cpp.o
.PHONY : src/Database.cpp.o

src/Database.i: src/Database.cpp.i
.PHONY : src/Database.i

# target to preprocess a source file
src/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Database.cpp.i
.PHONY : src/Database.cpp.i

src/Database.s: src/Database.cpp.s
.PHONY : src/Database.s

# target to generate assembly for a file
src/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Database.cpp.s
.PHONY : src/Database.cpp.s

src/HttpSession.o: src/HttpSession.cpp.o
.PHONY : src/HttpSession.o

# target to build an object file
src/HttpSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/HttpSession.cpp.o
.PHONY : src/HttpSession.cpp.o

src/HttpSession.i: src/HttpSession.cpp.i
.PHONY : src/HttpSession.i

# target to preprocess a source file
src/HttpSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/HttpSession.cpp.i
.PHONY : src/HttpSession.cpp.i

src/HttpSession.s: src/HttpSession.cpp.s
.PHONY : src/HttpSession.s

# target to generate assembly for a file
src/HttpSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/HttpSession.cpp.s
.PHONY : src/HttpSession.cpp.s

src/Listener.o: src/Listener.cpp.o
.PHONY : src/Listener.o

# target to build an object file
src/Listener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Listener.cpp.o
.PHONY : src/Listener.cpp.o

src/Listener.i: src/Listener.cpp.i
.PHONY : src/Listener.i

# target to preprocess a source file
src/Listener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Listener.cpp.i
.PHONY : src/Listener.cpp.i

src/Listener.s: src/Listener.cpp.s
.PHONY : src/Listener.s

# target to generate assembly for a file
src/Listener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Listener.cpp.s
.PHONY : src/Listener.cpp.s

src/RateLimiter.o: src/RateLimiter.cpp.o
.PHONY : src/RateLimiter.o

# target to build an object file
src/RateLimiter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/RateLimiter.cpp.o
.PHONY : src/RateLimiter.cpp.o

src/RateLimiter.i: src/RateLimiter.cpp.i
.PHONY : src/RateLimiter.i

# target to preprocess a source file
src/RateLimiter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/RateLimiter.cpp.i
.PHONY : src/RateLimiter.cpp.i

src/RateLimiter.s: src/RateLimiter.cpp.s
.PHONY : src/RateLimiter.s

# target to generate assembly for a file
src/RateLimiter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/RateLimiter.cpp.s
.PHONY : src/RateLimiter.cpp.s

src/WSSession.o: src/WSSession.cpp.o
.PHONY : src/WSSession.o

# target to build an object file
src/WSSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/WSSession.cpp.o
.PHONY : src/WSSession.cpp.o

src/WSSession.i: src/WSSession.cpp.i
.PHONY : src/WSSession.i

# target to preprocess a source file
src/WSSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/WSSession.cpp.i
.PHONY : src/WSSession.cpp.i

src/WSSession.s: src/WSSession.cpp.s
.PHONY : src/WSSession.s

# target to generate assembly for a file
src/WSSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/WSSession.cpp.s
.PHONY : src/WSSession.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ChatRoom.o"
	@echo "... src/ChatRoom.i"
	@echo "... src/ChatRoom.s"
	@echo "... src/Database.o"
	@echo "... src/Database.i"
	@echo "... src/Database.s"
	@echo "... src/HttpSession.o"
	@echo "... src/HttpSession.i"
	@echo "... src/HttpSession.s"
	@echo "... src/Listener.o"
	@echo "... src/Listener.i"
	@echo "... src/Listener.s"
	@echo "... src/RateLimiter.o"
	@echo "... src/RateLimiter.i"
	@echo "... src/RateLimiter.s"
	@echo "... src/WSSession.o"
	@echo "... src/WSSession.i"
	@echo "... src/WSSession.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

